name: Deploy with old react-currency version

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"  

      - name: Install dependencies
        run: npm install react-currency-format@1.1.0

      - name: Build and deploy
        run: |
          npm run build
          # Add deployment command(s) here
